/* ABI-ONLINE FALLBACK DATEN 
    Ausgelagert aus logic.js für bessere Übersicht.
    Enthält Standard-Formeln und Snippets für den Offline-Modus.
    
    HINWEIS ZU DEN SNIPPETS:
    Vielen Block-Elementen (Tabellen, Boxen) wurde am Ende ein 
    <p>&nbsp;</p> angefügt. Das sorgt dafür, dass man im Editor 
    leicht unter den Kasten klicken kann, um weiterzuschreiben.
*/

window.FALLBACK_FORMELN_CSV = `
Kategorie;Titel;Inhalt
Analysis;Nullstellen; §§f(x)=0§§ 
Analysis;Ableitung; §§f'(x)§§ 
Analysis;Extrema (Notw.); §§f'(x)=0§§ 
Analysis;Integral; §§int_a^b f(x) dx§§ 
Vektoren;Vektor (3D); §§vec a = ((x_1),(x_2),(x_3))§§ 
Vektoren;Skalarprodukt; §§vec a * vec b = 0§§ 
Vektoren;Ebene (Parameter); §§E: vec x = vec p + r * vec u + s * vec v§§ 
Grundlagen;Wurzel; §§sqrt(x)§§ 
Grundlagen;Bruch; §§a/b§§ 
Grundlagen;pq-Formel; §§x_{1,2} = -p/2 +- sqrt((p/2)^2 - q)§§
`;

window.FALLBACK_SNIPPETS_CSV = `
Titel<spaltenwechsel>Code<spaltenwechsel>Tooltip<spaltenwechsel>Trenner
Skizze<spaltenwechsel>__SKIZZE__<spaltenwechsel>Freihandzeichnung<spaltenwechsel>false
Uhrzeit (Text)<spaltenwechsel>__UHRZEIT__<spaltenwechsel>Fügt aktuelle Zeit ein<spaltenwechsel>false
Datum (Text)<spaltenwechsel>__DATUM__<spaltenwechsel>Fügt aktuelles Datum ein<spaltenwechsel>true
Lernziele<spaltenwechsel><div style="background-color:#f0fdf4; border-left:4px solid #16a34a; padding:12px; margin:10px 0; border-radius:0 4px 4px 0;"><strong style="color:#15803d;">🎯 Lernziele für heute:</strong><ul style="margin-bottom:0; padding-left:20px; margin-top:5px; color:#166534;"><li>...</li><li>...</li></ul></div><p>&nbsp;</p><spaltenwechsel>Grüne Lernziele-Box<spaltenwechsel>false
Hausaufgabe<spaltenwechsel><div style="background-color:#eff6ff; border:1px solid #3b82f6; border-radius:8px; padding:15px; margin:10px 0;"><h4 style="margin:0 0 8px 0; color:#1d4ed8;">🏠 Hausaufgabe</h4><p style="margin:0; color:#1e40af;">Bis zum nächsten Mal:<br>S. 123 Nr. 1, 2</p></div><p>&nbsp;</p><spaltenwechsel>Blaue HA-Box<spaltenwechsel>false
Merke<spaltenwechsel><div style="background-color:#fffbeb; border-left:4px solid #f59e0b; padding:12px; margin:10px 0; color:#92400e;"><strong>💡 Merke:</strong><br>Hier steht eine wichtige Regel oder Definition.</div><p>&nbsp;</p><spaltenwechsel>Gelber Merke-Kasten<spaltenwechsel>false
Wichtig<spaltenwechsel><div style="background-color:#fef2f2; border:1px solid #ef4444; color:#b91c1c; padding:10px; border-radius:4px; margin:10px 0; display:flex; gap:10px; align-items:center;"><span style="font-size:1.5em;">⚠️</span><div><strong>Achtung:</strong> Das ist prüfungsrelevant!</div></div><p>&nbsp;</p><spaltenwechsel>Rote Warnbox<spaltenwechsel>true
Pro-Kontra<spaltenwechsel><table style="width:100%; border-collapse:collapse; margin:10px 0; border:1px solid #cbd5e1;"><thead><tr style="background:#f1f5f9;"><th style="border:1px solid #cbd5e1; padding:8px; width:50%; color:#166534;">👍 Pro</th><th style="border:1px solid #cbd5e1; padding:8px; width:50%; color:#991b1b;">👎 Kontra</th></tr></thead><tbody><tr><td style="border:1px solid #cbd5e1; padding:8px; vertical-align:top;">• </td><td style="border:1px solid #cbd5e1; padding:8px; vertical-align:top;">• </td></tr></tbody></table><p>&nbsp;</p><spaltenwechsel>Tabelle Pro/Kontra<spaltenwechsel>false
Vokabeln<spaltenwechsel><table style="width:100%; border-collapse:collapse; margin:10px 0;"><thead style="background:#f8fafc; color:#475569;"><tr><th style="border-bottom:2px solid #e2e8f0; padding:8px; text-align:left;">Begriff</th><th style="border-bottom:2px solid #e2e8f0; padding:8px; text-align:left;">Erklärung</th></tr></thead><tbody><tr><td style="padding:8px; border-bottom:1px solid #e2e8f0;">...</td><td style="padding:8px; border-bottom:1px solid #e2e8f0;">...</td></tr><tr><td style="padding:8px; border-bottom:1px solid #e2e8f0;">...</td><td style="padding:8px; border-bottom:1px solid #e2e8f0;">...</td></tr></tbody></table><p>&nbsp;</p><spaltenwechsel>Vokabelliste<spaltenwechsel>true
Checkliste<spaltenwechsel><ul style="list-style:none; padding:0; margin:10px 0;"><li><input type="checkbox"> Aufgabe gelesen</li><li><input type="checkbox"> Text markiert</li><li><input type="checkbox"> Fragen beantwortet</li></ul><p>&nbsp;</p><spaltenwechsel>Abhak-Liste<spaltenwechsel>false
Feedback<spaltenwechsel><div style="border:1px solid #e2e8f0; padding:10px; border-radius:8px; margin:10px 0;"><strong style="display:block; margin-bottom:5px; color:#475569;">Kurzfeedback:</strong><table style="width:100%; border-collapse:collapse; font-size:0.9em;"><tr><td style="padding:5px; border-bottom:1px solid #eee;">Inhalt / Verständnis</td><td style="padding:5px; border-bottom:1px solid #eee; text-align:right;">🙂 😐 🙁</td></tr><tr><td style="padding:5px; border-bottom:1px solid #eee;">Sprachliche Richtigkeit</td><td style="padding:5px; border-bottom:1px solid #eee; text-align:right;">🙂 😐 🙁</td></tr><tr><td style="padding:5px; border-bottom:1px solid #eee;">Mitarbeit</td><td style="padding:5px; border-bottom:1px solid #eee; text-align:right;">🙂 😐 🙁</td></tr></table></div><p>&nbsp;</p><spaltenwechsel>Feedback-Raster<spaltenwechsel>false
Unterschrift<spaltenwechsel><div style="margin-top:40px; margin-bottom:20px;"><div style="border-top:1px solid #000; width:250px; padding-top:5px; font-size:0.8em; color:#555;">Ort, Datum / Unterschrift Erziehungsberechtigte</div></div><p>&nbsp;</p><spaltenwechsel>Linie für Unterschrift<spaltenwechsel>true
2-Spalten<spaltenwechsel><div style="display:flex; gap:20px; flex-wrap:wrap;"><div style="flex:1; min-width:200px;"><strong>Links</strong><br>Text hier...</div><div style="flex:1; min-width:200px;"><strong>Rechts</strong><br>Text hier...</div></div><p>&nbsp;</p><spaltenwechsel>Spalten-Layout<spaltenwechsel>false
Zitat<spaltenwechsel><blockquote style="border-left:4px solid #94a3b8; background:#f8fafc; margin:10px 0; padding:10px 15px; font-style:italic; color:#334155;">„Das Zitat hier einfügen.“<footer style="margin-top:5px; font-size:0.8em; font-style:normal; color:#64748b;">— Quelle</footer></blockquote><p>&nbsp;</p><spaltenwechsel>Zitatblock<spaltenwechsel>false
JS Hello<spaltenwechsel><pre style="background:#1e1e1e; color:#dcdcdc; padding:10px; border-radius:5px; font-family:monospace; overflow-x:auto;"><code>console.log("Hallo Welt");</code></pre><p>&nbsp;</p><spaltenwechsel>Code Block<spaltenwechsel>false
Uhr (Standard)<spaltenwechsel><div class="live-clock" contenteditable="false" style="display:inline-block; width:80px; height:80px; border:2px solid #334155; border-radius:50%; position:relative; background:white; vertical-align:middle; box-shadow:0 2px 4px rgba(0,0,0,0.1); cursor:move;"><div class="clock-hour" style="position:absolute; bottom:50%; left:calc(50% - 2px); width:4px; height:25%; background:#334155; transform-origin:bottom center; transform:rotate(0deg); border-radius:2px;"></div><div class="clock-min" style="position:absolute; bottom:50%; left:calc(50% - 1.5px); width:3px; height:35%; background:#334155; transform-origin:bottom center; transform:rotate(0deg); border-radius:2px;"></div><div class="clock-sec" style="position:absolute; bottom:50%; left:calc(50% - 1px); width:2px; height:40%; background:#dc2626; transform-origin:bottom center; transform:rotate(0deg);"></div><div style="position:absolute; top:50%; left:50%; width:8px; height:8px; background:#334155; border-radius:50%; transform:translate(-50%, -50%);"></div></div><spaltenwechsel>Mit Sekundenzeiger<spaltenwechsel>false
Timer (Interaktiv)<spaltenwechsel><div class="live-timer" contenteditable="false" data-time="300" data-active="false" style="display:inline-flex; flex-wrap:wrap; align-items:center; gap:6px; padding:6px 10px; background:#fefce8; border:2px solid #facc15; border-radius:8px; color:#854d0e; font-weight:bold; cursor:move; user-select:none; max-width: 350px;"><span style="font-size:1.2em;">⏱️</span> <span class="timer-display" style="font-family:monospace; font-size:1.4em; min-width:60px; text-align:center; background:#fff; border:1px solid #eab308; border-radius:4px; padding:0 4px;">05:00</span> <div style="display:flex; gap:2px;"><button class="timer-btn-add" data-add="60" style="background:#fef08a; border:1px solid #eab308; border-radius:3px; cursor:pointer; font-size:0.75em; padding:2px 4px;">+1m</button><button class="timer-btn-add" data-add="300" style="background:#fef08a; border:1px solid #eab308; border-radius:3px; cursor:pointer; font-size:0.75em; padding:2px 4px;">+5m</button><button class="timer-btn-add" data-add="-60" style="background:#fef08a; border:1px solid #eab308; border-radius:3px; cursor:pointer; font-size:0.75em; padding:2px 4px;">-1m</button></div> <div style="width:1px; height:20px; background:#ca8a04; margin:0 4px;"></div> <button class="timer-control" style="background:#facc15; border:none; border-radius:4px; cursor:pointer; padding:4px 8px; font-size:0.8em; font-weight:bold;">Start</button> <button class="timer-reset" style="background:transparent; border:1px solid #ca8a04; border-radius:4px; cursor:pointer; padding:4px 8px; font-size:0.8em; color:#854d0e;">Reset</button></div><spaltenwechsel>Mit +/- Tasten<spaltenwechsel>false
Timer (10 Sek)<spaltenwechsel><div class="live-timer" contenteditable="false" data-time="10" data-active="false" style="display:inline-flex; flex-wrap:wrap; align-items:center; gap:6px; padding:6px 10px; background:#fefce8; border:2px solid #facc15; border-radius:8px; color:#854d0e; font-weight:bold; cursor:move; user-select:none; max-width: 350px;"><span style="font-size:1.2em;">⚡</span> <span class="timer-display" style="font-family:monospace; font-size:1.4em; min-width:60px; text-align:center; background:#fff; border:1px solid #eab308; border-radius:4px; padding:0 4px;">00:10</span> <button class="timer-control" style="background:#facc15; border:none; border-radius:4px; cursor:pointer; padding:4px 8px; font-size:0.8em; font-weight:bold;">Start</button> <button class="timer-reset" style="background:transparent; border:1px solid #ca8a04; border-radius:4px; cursor:pointer; padding:4px 8px; font-size:0.8em; color:#854d0e;">Reset</button></div><spaltenwechsel>Schnelltest<spaltenwechsel>false
Container (Rechts)<spaltenwechsel><div style="float:right; margin:0 0 10px 15px; padding:15px; border:1px dashed #cbd5e1; background:#f8fafc; border-radius:8px; width:220px;"><p style="margin-top:0;"><strong>Info-Box</strong></p><p>Hier kann Text stehen, der vom Haupttext umflossen wird.</p></div><p>&nbsp;</p><spaltenwechsel>Schwebender Kasten<spaltenwechsel>false
`;